update with fixes

diff --git a/pop b/pop
--- a/pop
+++ b/pop
@@ -1,6 +1,6 @@
 #!/bin/bash
-# v3.8 by looneytkp™
-set -xe
+# v4.0 by looneytkp™
+set -e
 NC='\033[0m';Y='\033[1;33m';LC='\033[1;36m';LR='\033[1;31m';LB='\033[1;34m';LG='\033[1;32m';bit=$(uname -m)
 shopt -u nocasematch
 
@@ -64,7 +64,7 @@ echo;exit
 }
 
 check() { curl -X POST -s --show-error -o out www.google.com 2> check | printf "";if grep -q "(6)" check;then
-echo;echo "- No internet connection";rm check;echo "- Exiting...";sleep 0.5;echo;exit;fi;
+echo;sleep .8;echo "- No internet connection";rm check;echo "- Exiting...";sleep 0.5;echo;exit;fi;
 }
 
 start() {
@@ -127,34 +127,47 @@ extract
 else echo;exit;fi;fi
 }
 
+reinstall() {
+read -p "- Reinstall ? (Y)es/(N)o > " rs
+case $rs in
+    y|yes) if [ $bit = "x86_64" ];then install64;else install32;fi;;
+    n|no) echo;exit;;
+esac
+}
+
 if [ $bit = "x86_64" ];then start64;else start32;fi
 if [ -d ~/popcorntime ];then cd ~/popcorntime;
     echo "- Installation directory present"
-    ls > output
-    size=$(wc -l <output)
+    ls > directory_check
+    size=$(wc -l <directory_check)
     if [ $size -lt 10 ]; then if [ $bit = "x86_64" ];then
-        rm output;install64;exit;
+        rm directory_check;install64;exit;
     else
-        rm output;install32;exit;fi
+        rm directory_check;install32;exit;fi
     fi
-    echo "- Checking directories...";echo;sleep .5
-    directories="lib locales node_modules pnacl src"
-    set -- $directories
-    for a in "$@"
-        do
-            if [ -d $a ]; then
-                sleep .2
-                echo "- Directory $a exists"
-            else
-                sleep .2
-                echo "- Directory $a does not exist"
-                echo
-                echo "- Reinstalling..."
-                if [ $bit = "x86_64" ];then install64;else install32;fi
-            fi
-        done
-    echo
-    echo "- Done";echo "- Checking files..."; echo
+    rm directory_check
+    printf "%b" "- Checking directories";echo;sleep .5
+    DIR="lib locales node_modules pnacl src"
+    if [ -d lib -a -d locales -a -d node_modules -a -d pnacl -a -d src ];then
+        zip -r1q zip.zip $DIR
+        old="ab6b6a01a9e4ab3468fd2be00241dafe"
+        new=$(md5sum zip.zip|sed "s_ .*__")
+        if [ $new == $old ];then
+            sleep .5
+            echo "- No errors found"
+            rm zip.zip
+            echo
+        else
+            echo "- Error found"
+            rm zip.zip
+            reinstall
+        fi
+    else
+        echo "- Error found"
+        rm zip.zip
+        reinstall
+    fi
+    echo "- Checking files..."; echo
     files="chromedriver icudtl.dat minidump_stackwalk nacl_helper nacl_helper_bootstrap nacl_irt_x86_64.nexe natives_blob.bin nw_100_percent.pak nw_200_percent.pak nwjc package.json payload Popcorn-Time resources.pak snapshot_blob.bin .git.json"
     set -- $files
     for a in "$@"
@@ -166,8 +179,11 @@ if [ -d ~/popcorntime ];then cd ~/popcorntime;
             sleep .2
             echo "- File $a does not exist"
             echo
-            echo "- Reinstalling..."
-            if [ $bit = "x86_64" ];then install64;else install32;fi
+            read -p "- Reinstall ? (Y)es/(N)o > " rs
+            case $rs in
+                y|yes) if [ $bit = "x86_64" ];then install64;else install32;fi;;
+                n|no) echo;exit;;
+            esac
         fi
     done
     echo "- Done"; echo
