made major changes

diff --git a/popcorn64 b/popcorn64
--- a/popcorn64
+++ b/popcorn64
@@ -1,30 +1,31 @@
 #!/bin/bash
-#script 4.3 final by LooNeyTKp™
-#exits shell when there is an error
+# v5.0 final by looneytkp™
+
 set -e
-#color
-NC='\033[0m' # No Color
-YELLOW='\033[1;33m'
-LIGHT_CYAN='\033[1;36m'
-startscript() {
+NC='\033[0m'
+Y='\033[1;33m'
+LC='\033[1;36m'
+LR='\033[1;31m'
+bashh='#!/bin/bash'
+strtscrpt() {
 sleep 0.5
 echo -e "
 "
-startinstall
+strtinst
 }
-startinstall() {
-echo -e "                    ${LIGHT_CYAN}Popcorn Time for 64bit${YELLOW}"
+strtinst() {
+echo -e "                    ${LC}Popcorn Time for 64bit PC"
+echo -e "                                 by looneytkp${Y}"
 echo
 cd ~
 if [ -d popcorntime ]; then
-rm -r popcorntime && mkdir popcorntime
-else
-mkdir popcorntime
+  rm -r popcorntime && mkdir popcorntime
+  else
+  mkdir popcorntime
 fi
 cd -
-cp Popcorn-Time-64.tar.xz /home/$USER/popcorntime/
+cp Popcorn-Time-64* /home/$USER/popcorntime/Popcorn-Time-64.tar.xz
 cd /home/$USER/popcorntime
-#unpacking popcorn time archive
 echo "Installing..."
 tar xf Popcorn-Time-64.tar.xz &
 pid=$! # Process Id of the running command
@@ -36,18 +37,15 @@ do
   printf "#"
   sleep .4
 done
-/bin/echo -e "]
-Done!"${NC}
-#delete Popcorn-Time-0.3.10-Linux-32.tar.xz in /popcorntime
-rm Popcorn-Time-0.3.10-Linux-64.tar.xz
-create
+echo -e "] Done!"
+rm Popcorn-Time-64.tar.xz
+crt
 }
-create() {
-			createdesktopentry;
+crt() {
+			cde;
 			sleep 1
 }
-# Adds a desktop entry for the current user
-createdesktopentry() {
+cde() {
 	NAME="Popcorn Time"
 	COMMENT="Watch Movies and TV Shows instantly!"
 
@@ -68,46 +66,70 @@ createdesktopentry() {
 	echo "Categories=Multimedia;" >> $DESKTOP_FILE
 	echo "Terminal=false" >> $DESKTOP_FILE
 }
-launch() {
-/bin/echo -e "${LIGHT_CYAN}Launch Popcorn Time ?" && read -p "(Y)es/(N)o > " RESP;
-#input list for yes
-if [ "$RESP" = "y" ] || [ "$RESP" = "Y" ] || [ "$RESP" = "yes" ] || [ "$RESP" = "YES" ] || [ "$RESP" = "Yes" ];
-then
-    sleep 1
-    /bin/echo -e "Launching..."
-    ./Popcorn-Time
-    installcomplete
-fi
-#input list for no
-if [ "$RESP" = "n" ] || [ "$RESP" = "N" ] || [ "$RESP" = "no" ] || [ "$RESP" = "NO" ] || [ "$RESP" = "No" ];
-then
-installcomplete
-fi
-if [ "$RESP" != "y" ] || [ "$RESP" != "Y" ] ||  "$RESP" != "yes" ] ||  "$RESP" != "YES" ] ||  "$RESP" != "Yes" ] ||  "$RESP" != "n" ] ||  "$RESP" != "N" ] ||  "$RESP" != "no" ] ||  "$RESP" != "NO" ] ||[ "$RESP" != "" ];  then
-/bin/echo -e "Invalid input" && launchtrap
-fi
-}
-launchtrap() {
-while :
-do
-trap launch EXIT
-break
-done
-}
-installcomplete() {
+lch() {
 echo
+shopt -u nocasematch
+printf "${Y}Launch Popcorn Time ?" && read -p "(Y)es/(N)o > " resp;
+case $resp in
+    y|yes) sleep 1
+       echo "Launching..."
+       ./Popcorn-Time
+       instcomp;;
+    n|no) instcomp;;
+    *) echo "Invalid input" && lch;;
+esac
+}
+instcomp() {
 cd -
-/bin/echo -e "Grant root permission"
-./gtk-icon-cache
-echo
-sleep 0.5
+sudo gtk-update-icon-cache /usr/share/icons/hicolor
+#echo "$bashh
 
-/bin/echo -e "
-                    Installation complete!"
+#LB='\033[1;34m'
+#LG='\033[1;32m'
+#cd /home/looney/popcorntime
+#./Popcorn-Time
+#echo
+#echo "${LG}Type ${LB}popcorntime -r ${LG}to uninstall Popcorn Time."
+#case $rmv in
+#    r)
+#      rm -r /home/$USER/popcorntime
+#sudo rm -f /usr/bin/popcorntime
+#sleep 0.3
+#echo \"${LG}Popcorn Time is uninstalled\"
+#echo \"Reinstall it again here: ${LB}https://github.com/looneytkp/popcorntime.git\"
+#exit 2;;
+#esac" > popcorntime
+#if [ ! -f /usr/bin/popcorntime ]; then
+#  sudo mv popcorntime /usr/bin/popcorntime
+#  cd /usr/bin
+#  sudo chmod 755 popcorntime
+#  else
+#      sudo rm /usr/bin/popcorntime
+#      sudo mv popcorntime /usr/bin/popcorntime
+#      cd /usr/bin
+#      sudo chmod 755 popcorntime
+#fi
+echo && sleep 0.5
+echo -e "${LC}GTK icon cache updated, you should find Popcorn Time in your applist."
+echo -e "Also typing ${Y}popcorntime ${LC}in terminal will launch Popcorn Time."
+echo "Enjoy :)"
+sleep 0.5 && echo
+echo "                    Installation complete!"
 echo
 sleep 1
-exit 1
 }
-startscript
-launch
-#script complete
+if [ ! -f Popcorn-Time-64* ]; then
+  sleep 0.7 && echo
+  echo -e "${LR}Popcome time installation file not found!. Read instructions below"
+  echo && echo -e "${LC}#### 64bit PC"
+  echo "1. Put the downloaded file in the same folder where the popcorn64.sh script is."
+  echo "   Or create a specific folder and place both files in it."
+  echo
+  echo -e "2. Double click and run the "${Y}popcorn64" ${LC}script."
+  echo -e "   Or open terminal in that particular folder and type "${Y}bash popcorn64"${LC}."
+  echo -e "3. Enjoy..."
+  echo && exit 2;
+  else
+      strtscrpt
+      lch
+fi
